modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="bimken"
version="${file.jarVersion}"
displayName="Bimken"
logoFile="examplemod.png"
credits="Special thanks to Dwayne 'The Rock' Johnson for his acting."
authors="b_e_a_n_, Bimblefwip"
description='''
Bimken.
You figure it out.
'''
[[dependencies.bimken]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.bimken]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
